"""relation one to manu betewen user and product

Revision ID: cadbfe43db94
Revises: 6324c023c0be
Create Date: 2022-12-07 22:01:14.152365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cadbfe43db94'
down_revision = '6324c023c0be'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_user', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user', type_='foreignkey')

    # ### end Alembic commands ###
